In [3]:
#created the 11.02.2020 in class.

In [4]:
#libraries/packages and working directory. Panda is a lib. 
#To do this you need to use the import.
# you instal it once, but you need to reimport every time you create new notebook
# os is good to see where your scrip is running on your computer. 

import os
os.getcwd()
#os.listdir()
#shows what is also saved in the folder as the notebook. 

#os.chdir(path)
#you can change the place the file will be saved, need to write path in the ().

'C:\\Users\\Bruger\\OneDrive - Københavns Universitet\\Dokumenter\\8. semester\\python'

In [2]:
import pandas as pd
import numpy as np
import json

In [3]:
df = pd.read_csv("data/100-Brexit-Tweets.csv")
df

,ID,json_file,json_pos,processed_at,user_id,user_handle,user_loc,user_desc,tweet_text,tweet_id,...,qu_user_desc,qu_tweet_text,qu_tweet_id,qu_tweet_time,qu_tweet_geo,qu_tweet_country,qu_tweet_loc,qu_tweet_loc_type,qu_tweet_hashtags,qu_tweet_mentions
0,1.0,2019-05-29_10-17-41,0,19/09/2019 10:39,2.520628e+08,John_Perry_UK,Havant Constituency,"2015, 2017 & 20xx GE Candidate. Havant Residen...",NaN,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
1,2.0,2019-05-29_10-17-41,1,19/09/2019 10:39,2.471046e+09,Jeankellie1,NaN,NaN,NaN,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
2,3.0,2019-05-29_10-17-41,2,19/09/2019 10:39,8.563300e+17,Mash_uk77,Manor park,"Father of three, joined labour after JC was el...",#RT PeterStefanovi2: RT Harryslaststand: With ...,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
3,4.0,2019-05-29_10-17-41,3,19/09/2019 10:39,3.075387e+09,w0rldlyw1se,England - UK - Out of EU,Topical comment on topical matters. Many a tru...,NaN,1.133630e+18,...,"Secretary of State for Environment, Food and R...",All Conservatives should take heed of John Cur...,1.133400e+18,28/05/2019 15:47,False,NaN,NaN,NaN,Gove4PM ReadyToLead,NaN
4,5.0,2019-05-29_10-17-41,4,19/09/2019 10:39,8.828850e+17,TheLeftWingUK,United Kingdom,#leftwing #politics news aggregator. Get the n...,John Bercow defies Eurosceptics with vow to st...,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,96.0,2019-05-29_10-17-41,90,19/09/2019 10:39,9.880684e+08,yoakumgirl923,"Texas, USA",Blocked by Michael Avenatti for thanking him f...,NaN,1.133630e+18,...,"News, commentary, and destruction of the polit...",Exclusive: @MLP_officiel tells @mboyle1 “Macro...,1.133090e+18,27/05/2019 19:18,False,NaN,NaN,NaN,NaN,mboyle1 MLP_officiel
97,97.0,2019-05-18_14-23-50,5,19/09/2019 10:39,1.842798e+07,bridgetmck,"London, England","Director @Flow_ers1 Museums, arts, learning, f...",NaN,1.129700e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
98,98.0,2019-05-29_10-17-41,91,19/09/2019 10:39,8.235065e+07,marciojmsilva,"Lousada, Portugal","Living life, one day after another. One day at...",Primeira-ministra britânica urge sucessor a pr...,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
99,99.0,2019-05-18_14-23-50,6,19/09/2019 10:39,9.883110e+17,boxster_porsche,Earth,Live\nLove\nForgive\nDrive,NaN,1.129700e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
100,100.0,2019-05-29_10-17-41,92,19/09/2019 10:39,8.738730e+17,Rene16437696,Midlothian Scotland,Happily retired.snp http://member.love Scotlan...,NaN,1.133630e+18,...,The best of the BBC's political coverage. Find...,"""WTO terms are nothing to be frightened of. We...",1.133320e+18,28/05/2019 10:33,True,NaN,NaN,NaN,Brexit,NaN

In [7]:
df.columns
len(df)

101

In [8]:
df.index

RangeIndex(start=0, stop=101, step=1)

In [9]:
#df.loc[[rows], [columns]]
df.loc[[0,1,2], ["json_file","ID"]]

             json_file   ID
0  2019-05-29_10-17-41  1.0
1  2019-05-29_10-17-41  2.0
2  2019-05-29_10-17-41  3.0

In [56]:
df.loc[:, ["tweet_type"]]

    tweet_type
0      Retweet
1      Retweet
2        Tweet
3     Re_Quote
4        Tweet
..         ...
96    Re_Quote
97     Retweet
98       Tweet
99     Retweet
100   Re_Quote

[101 rows x 1 columns]

In [65]:
df.loc[df.loc[:, "tweet_type"] == "Tweet", "tweet_text"]

2     #RT PeterStefanovi2: RT Harryslaststand: With ...
4     John Bercow defies Eurosceptics with vow to st...
5                                                #NAME?
7     @MartinDaubney I shouldn't worry, Martin, most...
8     New post: "UK PM candidate Hancock says no-dea...
11    New post: "No-deal Brexit tangled: UK House of...
19    @BBCr4today @lisanandy and BBCr4today chooses ...
22    R/T NicolaSturgeon RT merrionstreet: An Taoise...
25    Britain is in the grip of an existential crisi...
27    Would No-Deal Brexit Really Be That Terrible F...
34    R/T NicolaSturgeon RT ScotGovFM: From her meet...
44    As an Apolitical organisation, our view is tha...
53    Businesses already bewildered by the Brexit de...
56    Another Conservative leadership contender. The...
57    @emmasnosey But are all Tories Brexiteers?  I ...
63    Tusk says Brexit served as 'vaccine' against e...
65    'Seismic shift': Labour voters in Wigan turn t...
66                                               #NAME?
73    Britain is in the grip of an existential crisi...
75    "Could there be, just about, a way through if ...
76    @vestager @TimmermansEU @BasEickhout Voter tur...
92                                               #NAME?
98    Primeira-ministra britânica urge sucessor a pr...
Name: tweet_text, dtype: object

In [11]:
df.loc[:, "tweet_geo"]

0       TRUE
1      FALSE
2       TRUE
3      FALSE
4      FALSE
       ...
96      TRUE
97     FALSE
98      TRUE
99     FALSE
100    FALSE
Name: tweet_geo, Length: 101, dtype: object

In [12]:
df.loc[df.loc[:, "tweet_geo"] == "TRUE", "user_handle"]

0       John_Perry_UK
2           Mash_uk77
5       MatthewRose86
6            cmogg623
15        DaveWebber3
17        carol_hulme
22           GovanSnp
25        manojpallai
26         Akiin_1905
31      AllenOwens123
34           GovanSnp
47       jdminiatures
53          bpolitics
54           DawnieR2
58           Sunwiser
59        carol_hulme
61       SewellMartin
65        manojpallai
66         DrJimboNHS
67    TheAccidentMan9
70      JeromeDavies1
71         TedTootill
73        terryturvey
74      aaronsonglass
78     RogerHelmerMEP
81            Pgdelr1
82          Macetrain
85       MarcusKohler
89      AntWadebridge
93         Lizzier459
96      yoakumgirl923
98      marciojmsilva
Name: user_handle, dtype: object

In [6]:
#(1) list contain cntaining all user_handles in the panda daaframe
# (1) Create a new list containing all user_handles in the pandas
# DataFrame by using the subsetting techniques showed above. Check 
# what type the newly created object is, and to turn it into a 'list'
# Tipp: Use Google to find out how to turn an python into a list
df.loc[:, "user_handle"]

0        John_Perry_UK
1          Jeankellie1
2            Mash_uk77
3          w0rldlyw1se
4        TheLeftWingUK
            ...
96       yoakumgirl923
97          bridgetmck
98       marciojmsilva
99     boxster_porsche
100       Rene16437696
Name: user_handle, Length: 101, dtype: object

In [7]:
handles = df.loc[:, "user_handle"]

In [13]:
handles

0        John_Perry_UK
1          Jeankellie1
2            Mash_uk77
3          w0rldlyw1se
4        TheLeftWingUK
            ...
96       yoakumgirl923
97          bridgetmck
98       marciojmsilva
99     boxster_porsche
100       Rene16437696
Name: user_handle, Length: 101, dtype: object

In [9]:
type(handles)

pandas.core.series.Series

In [10]:
handleslist = handles.values.tolist()
# could also write handles = list(handles)

In [11]:
type(handleslist)
#something close to a list, but a index as it has numbers
df.columns

Index(['ID', 'json_file', 'json_pos', 'processed_at', 'user_id', 'user_handle',
       'user_loc', 'user_desc', 'tweet_text', 'tweet_id', 'tweet_time',
       'tweet_geo', 'tweet_country', 'tweet_loc', 'tweet_loc_type',
       'tweet_lang', 'tweet_type', 'tweet_hashtags', 'tweet_mentions',
       're_user_id', 're_user_handle', 're_user_loc', 're_user_desc',
       're_tweet_text', 're_tweet_id', 're_tweet_time', 're_tweet_geo',
       're_tweet_country', 're_tweet_loc', 're_tweet_loc_type',
       're_tweet_hashtags', 're_tweet_mentions', 'qu_user_id',
       'qu_user_handle', 'qu_user_loc', 'qu_user_desc', 'qu_tweet_text',
       'qu_tweet_id', 'qu_tweet_time', 'qu_tweet_geo', 'qu_tweet_country',
       'qu_tweet_loc', 'qu_tweet_loc_type', 'qu_tweet_hashtags',
       'qu_tweet_mentions'],
      dtype='object')

In [14]:
# (2) Create a new list containing all the tweet_text where tweet_type
# is equal to "Tweet". I.e., filter out all Retweets, Quotes, Retweeted 
# Quotes, etc. in order to get only at the original Tweets
# Tipp: Use the same Boolean logic as above to find out which rows to 
# keep and which ones to discard.
df.loc[:, "tweet_type"]

0       Retweet
1       Retweet
2         Tweet
3      Re_Quote
4         Tweet
         ...
96     Re_Quote
97      Retweet
98        Tweet
99      Retweet
100    Re_Quote
Name: tweet_type, Length: 101, dtype: object

In [17]:
df.loc[df.loc[:, "tweet_type"] == "Tweet", "tweet_text"]

2     #RT PeterStefanovi2: RT Harryslaststand: With ...
4     John Bercow defies Eurosceptics with vow to st...
5                                                #NAME?
7     @MartinDaubney I shouldn't worry, Martin, most...
8     New post: "UK PM candidate Hancock says no-dea...
11    New post: "No-deal Brexit tangled: UK House of...
19    @BBCr4today @lisanandy and BBCr4today chooses ...
22    R/T NicolaSturgeon RT merrionstreet: An Taoise...
25    Britain is in the grip of an existential crisi...
27    Would No-Deal Brexit Really Be That Terrible F...
34    R/T NicolaSturgeon RT ScotGovFM: From her meet...
44    As an Apolitical organisation, our view is tha...
53    Businesses already bewildered by the Brexit de...
56    Another Conservative leadership contender. The...
57    @emmasnosey But are all Tories Brexiteers?  I ...
63    Tusk says Brexit served as 'vaccine' against e...
65    'Seismic shift': Labour voters in Wigan turn t...
66                                               #NAME?
73    Britain is in the grip of an existential crisi...
75    "Could there be, just about, a way through if ...
76    @vestager @TimmermansEU @BasEickhout Voter tur...
92                                               #NAME?
98    Primeira-ministra britânica urge sucessor a pr...
Name: tweet_text, dtype: object

In [18]:
tweets = df.loc[df.loc[:, "tweet_type"] == "Tweet", "tweet_text"]
#could also write tweets = df.loc[df.loc[:, "tweet_type"] == "Tweet", "tweet_text"].tolist(), 
#this would make it a list right away

In [19]:
tweetslist = tweets.values.tolist()

In [20]:
tweetslist

['#RT PeterStefanovi2: RT Harryslaststand: With the detritus of our life together scattered around the living room in the apartment we once shared, I become acutely aware  of the hole my father’s death has torn open in my own existence.\nhttps://t.co/pcM0yax6iu #EUElectionResults',
 'John Bercow defies Eurosceptics with vow to stay on as Speaker\n\nExclusive: move likely to anger hardliners who fear Bercow wants to stop no-deal Brexit\n\nJohn Bercow has said he plans to stay in his post as Speaker of the House of Commons despite previous… https://t.co/bFLd9gwCGY',
 '#NAME?',
 "@MartinDaubney I shouldn't worry, Martin, most of the people in posh circles (including presenters) are very much part of the establishment and they all hate Brexit. You, however, have the majority of the normal people behind you.",
 'New post: "UK PM candidate Hancock says no-deal Brexit is not an option: FT" https://t.co/zy70GpVyIU',
 'New post: "No-deal Brexit tangled: UK House of Commons Speaker Bercow pledges to stay on" https://t.co/sB7iGP6cmi',
 "@BBCr4today @lisanandy and BBCr4today chooses to focus on Lisa Nandy again and again for reasons unclear- it's almost as if they had a pro Brexit agenda. \n\nhttps://t.co/3q7XSVaHxW",
 'R/T NicolaSturgeon RT merrionstreet: An Taoiseach and First Minister will discuss the latest political developments in the wake of the European elections, the latest #Brexit developments and reflect on the strength of the relationship between Ireland and… https://t.co/zb0jS18LBN',
 'Britain is in the grip of an existential crisis that reaches far beyond Brexit | Aditya Chakrabortty https://t.co/mR0CVgf132',
 'Would No-Deal Brexit Really Be That Terrible For The UK? https://t.co/j555oSy2iV #TCOT #GOP #MAGA',
 "R/T NicolaSturgeon RT ScotGovFM: From her meeting with the Taoiseach LeoVaradkar to a Q&amp;A on Brexit and women in leadership at the RIADawson - check out the highlights from NicolaSturgeon's trip to Dublin earlier this week. \n\n???????????????????? https://t.co/PAcDcqSWXg",
 "As an Apolitical organisation, our view is that you should think about the Country, not your careers. #sks8 number10 UKParliament There needs to be a constitutional reform to accommodate the modern world. Difficult times. Everyone's doing their best. #brexit SKS_Media …",
 'Businesses already bewildered by the Brexit debacle are bracing for more confusion https://t.co/3FgiV0UArc',
 'Another Conservative leadership contender. The Commons Speaker says he’s not going till Brexit is over. And more Labour figures say they voted for other parties in the European elections. For the latest join me now on @BBCBerkshire https://t.co/PMl5wtrk4r',
 '@emmasnosey But are all Tories Brexiteers?  I think not!\nYou can’t take anything from these results.  UKIP Voters and Brexit supporters moved to Brexit party and Remainers moved to Lib Dem’s and Greens.  Others are fed up with Brexit and are more interested in how we solve the real issues',
 "Tusk says Brexit served as 'vaccine' against eurosceptic EU vote https://t.co/E7YRNHztl7",
 "'Seismic shift': Labour voters in Wigan turn towards Brexit party https://t.co/bh1RB3RyQJ",
 '#NAME?',
 'Britain is in the grip of an existential crisis that reaches far beyond Brexit https://t.co/N0W25TwTQQ',
 '"Could there be, just about, a way through if MPs, and Brussels, are willing to compromise?"\n\nIn today\'s #SkyViews, BethRigby says politicians may have not liked the messenger, but Theresa May had a point on #Brexit.\n\nRead more here ??',
 "@vestager @TimmermansEU @BasEickhout Voter turnout confirms Theory Democratic Integration #EU is evolving from 'Union democ states' to #europeandemocracy Next steps are 4 EP to adapt 1976ElectionAct to Lisbon Treaty, 4 EUCO to respect SpitzKanPr &amp; 4 UK to solve Brexit. Read book: https://t.co/F5hizCkg9G",
 '#NAME?',
 'Primeira-ministra britânica urge sucessor a procurar consenso e a concretizar Brexit com acordo https://t.co/NTG7lLrSFL https://t.co/iUNRT2ISm9']

In [21]:
type(tweetslist)

list

In [22]:
tweets

2     #RT PeterStefanovi2: RT Harryslaststand: With ...
4     John Bercow defies Eurosceptics with vow to st...
5                                                #NAME?
7     @MartinDaubney I shouldn't worry, Martin, most...
8     New post: "UK PM candidate Hancock says no-dea...
11    New post: "No-deal Brexit tangled: UK House of...
19    @BBCr4today @lisanandy and BBCr4today chooses ...
22    R/T NicolaSturgeon RT merrionstreet: An Taoise...
25    Britain is in the grip of an existential crisi...
27    Would No-Deal Brexit Really Be That Terrible F...
34    R/T NicolaSturgeon RT ScotGovFM: From her meet...
44    As an Apolitical organisation, our view is tha...
53    Businesses already bewildered by the Brexit de...
56    Another Conservative leadership contender. The...
57    @emmasnosey But are all Tories Brexiteers?  I ...
63    Tusk says Brexit served as 'vaccine' against e...
65    'Seismic shift': Labour voters in Wigan turn t...
66                                               #NAME?
73    Britain is in the grip of an existential crisi...
75    "Could there be, just about, a way through if ...
76    @vestager @TimmermansEU @BasEickhout Voter tur...
92                                               #NAME?
98    Primeira-ministra britânica urge sucessor a pr...
Name: tweet_text, dtype: object

In [23]:
# (3) Check out the index of this newly created object. How would you
# select the first element of the list created in exercise 2? Can you
# find out why it does not follow the normal counting we would expect?
# does not follow as the new list first value fits with
# observation number 2

In [25]:
tweets.index

Int64Index([ 2,  4,  5,  7,  8, 11, 19, 22, 25, 27, 34, 44, 53, 56, 57, 63, 65,
            66, 73, 75, 76, 92, 98],
           dtype='int64')

In [27]:
len(tweets)

23

In [30]:
tweets.reset_index()

    index                                         tweet_text
0       2  #RT PeterStefanovi2: RT Harryslaststand: With ...
1       4  John Bercow defies Eurosceptics with vow to st...
2       5                                             #NAME?
3       7  @MartinDaubney I shouldn't worry, Martin, most...
4       8  New post: "UK PM candidate Hancock says no-dea...
5      11  New post: "No-deal Brexit tangled: UK House of...
6      19  @BBCr4today @lisanandy and BBCr4today chooses ...
7      22  R/T NicolaSturgeon RT merrionstreet: An Taoise...
8      25  Britain is in the grip of an existential crisi...
9      27  Would No-Deal Brexit Really Be That Terrible F...
10     34  R/T NicolaSturgeon RT ScotGovFM: From her meet...
11     44  As an Apolitical organisation, our view is tha...
12     53  Businesses already bewildered by the Brexit de...
13     56  Another Conservative leadership contender. The...
14     57  @emmasnosey But are all Tories Brexiteers?  I ...
15     63  Tusk says Brexit served as 'vaccine' against e...
16     65  'Seismic shift': Labour voters in Wigan turn t...
17     66                                             #NAME?
18     73  Britain is in the grip of an existential crisi...
19     75  "Could there be, just about, a way through if ...
20     76  @vestager @TimmermansEU @BasEickhout Voter tur...
21     92                                             #NAME?
22     98  Primeira-ministra britânica urge sucessor a pr...

In [26]:
print(tweetslist[0])

#RT PeterStefanovi2: RT Harryslaststand: With the detritus of our life together scattered around the living room in the apartment we once shared, I become acutely aware  of the hole my father’s death has torn open in my own existence.
https://t.co/pcM0yax6iu #EUElectionResults

In [75]:
df.iloc[[0, 2], [8]]

                                          tweet_text
0                                                NaN
2  #RT PeterStefanovi2: RT Harryslaststand: With ...

In [ ]:
#there is no value with tweet on row 0 and 1. 
#the first tweet is in row 2

In [34]:
# (4) Try to select the first element of this new list as it is. Try to
# find a way to reset the index of this pandas object to the standard
# counting.
# Tipp: Use Google...
df

,ID,json_file,json_pos,processed_at,user_id,user_handle,user_loc,user_desc,tweet_text,tweet_id,...,qu_user_desc,qu_tweet_text,qu_tweet_id,qu_tweet_time,qu_tweet_geo,qu_tweet_country,qu_tweet_loc,qu_tweet_loc_type,qu_tweet_hashtags,qu_tweet_mentions
0,1.0,2019-05-29_10-17-41,0,19/09/2019 10:39,2.520628e+08,John_Perry_UK,Havant Constituency,"2015, 2017 & 20xx GE Candidate. Havant Residen...",NaN,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
1,2.0,2019-05-29_10-17-41,1,19/09/2019 10:39,2.471046e+09,Jeankellie1,NaN,NaN,NaN,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
2,3.0,2019-05-29_10-17-41,2,19/09/2019 10:39,8.563300e+17,Mash_uk77,Manor park,"Father of three, joined labour after JC was el...",#RT PeterStefanovi2: RT Harryslaststand: With ...,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
3,4.0,2019-05-29_10-17-41,3,19/09/2019 10:39,3.075387e+09,w0rldlyw1se,England - UK - Out of EU,Topical comment on topical matters. Many a tru...,NaN,1.133630e+18,...,"Secretary of State for Environment, Food and R...",All Conservatives should take heed of John Cur...,1.133400e+18,28/05/2019 15:47,False,NaN,NaN,NaN,Gove4PM ReadyToLead,NaN
4,5.0,2019-05-29_10-17-41,4,19/09/2019 10:39,8.828850e+17,TheLeftWingUK,United Kingdom,#leftwing #politics news aggregator. Get the n...,John Bercow defies Eurosceptics with vow to st...,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,96.0,2019-05-29_10-17-41,90,19/09/2019 10:39,9.880684e+08,yoakumgirl923,"Texas, USA",Blocked by Michael Avenatti for thanking him f...,NaN,1.133630e+18,...,"News, commentary, and destruction of the polit...",Exclusive: @MLP_officiel tells @mboyle1 “Macro...,1.133090e+18,27/05/2019 19:18,False,NaN,NaN,NaN,NaN,mboyle1 MLP_officiel
97,97.0,2019-05-18_14-23-50,5,19/09/2019 10:39,1.842798e+07,bridgetmck,"London, England","Director @Flow_ers1 Museums, arts, learning, f...",NaN,1.129700e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
98,98.0,2019-05-29_10-17-41,91,19/09/2019 10:39,8.235065e+07,marciojmsilva,"Lousada, Portugal","Living life, one day after another. One day at...",Primeira-ministra britânica urge sucessor a pr...,1.133630e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
99,99.0,2019-05-18_14-23-50,6,19/09/2019 10:39,9.883110e+17,boxster_porsche,Earth,Live\nLove\nForgive\nDrive,NaN,1.129700e+18,...,NaN,NaN,0.000000e+00,01/01/1900 00:00,False,NaN,NaN,NaN,NaN,NaN
100,100.0,2019-05-29_10-17-41,92,19/09/2019 10:39,8.738730e+17,Rene16437696,Midlothian Scotland,Happily retired.snp http://member.love Scotlan...,NaN,1.133630e+18,...,The best of the BBC's political coverage. Find...,"""WTO terms are nothing to be frightened of. We...",1.133320e+18,28/05/2019 10:33,True,NaN,NaN,NaN,Brexit,NaN

In [38]:
tweets = tweets.reset_index(drop=True)
#true means deletes the old index, where normally the old index numbers 
# is saved as seen above
tweets

0     #RT PeterStefanovi2: RT Harryslaststand: With ...
1     John Bercow defies Eurosceptics with vow to st...
2                                                #NAME?
3     @MartinDaubney I shouldn't worry, Martin, most...
4     New post: "UK PM candidate Hancock says no-dea...
5     New post: "No-deal Brexit tangled: UK House of...
6     @BBCr4today @lisanandy and BBCr4today chooses ...
7     R/T NicolaSturgeon RT merrionstreet: An Taoise...
8     Britain is in the grip of an existential crisi...
9     Would No-Deal Brexit Really Be That Terrible F...
10    R/T NicolaSturgeon RT ScotGovFM: From her meet...
11    As an Apolitical organisation, our view is tha...
12    Businesses already bewildered by the Brexit de...
13    Another Conservative leadership contender. The...
14    @emmasnosey But are all Tories Brexiteers?  I ...
15    Tusk says Brexit served as 'vaccine' against e...
16    'Seismic shift': Labour voters in Wigan turn t...
17                                               #NAME?
18    Britain is in the grip of an existential crisi...
19    "Could there be, just about, a way through if ...
20    @vestager @TimmermansEU @BasEickhout Voter tur...
21                                               #NAME?
22    Primeira-ministra britânica urge sucessor a pr...
Name: tweet_text, dtype: object